# Hi and welcome to your first code along lesson!

### Reading, writing and display images with OpenCV 
Let's start by importing the OpenCV Library

In [1]:
# Press CTRL + Enter to run this line
# You should see an * between the [ ] on the left
# OpenCV takes a couple seconds to import the first time

import cv2

In [2]:
# Now let's import numpy
# We use as np, so That everything we call on numpy, we can type np instead

import numpy as np

In [3]:
# We don't need to do this again, but it's good habit
import cv2

# Load an image using 'imread' specifying the path to image
input = cv2.imread('./images/input.jpg')

# Our file 'input.jpg' is now loaded and stored in python
# as a variable we named 'image'

# To display our image variable, we use 'imshow'
# The first parameter will be title shown on image window
# The second parameter is the image variable
cv2.imshow('Hello World', input)

# 'waitkey' allows us to input information when a image window is open
# By leaving it blank it just waits for anykey to be pressed before
# continuing. By placing numbers (except 0), we can specify a delay for 
# how long you keep the window open (time is in milliseconds here)
cv2.waitKey()

# This closes all open windows
# Failure to place this will cause your program to hang
cv2.destroyAllWindows()

## Lets take a closer look at how images are stored

In [6]:
# Import numpy 
import numpy as np

In [8]:
print(input.shape)

(427, 640, 3)


In [9]:
# Let's print each dimension of the image

print('Heigh of the Image: ', int(input.shape[0]), 'pixels') 
print('Width of the Image: ', int(input.shape[1]), 'pixels') 

Heigh of the Image:  427 pixels
Width of the Image:  640 pixels


In [10]:
print(input)

[[[ 81 115 139]
  [ 71  96 136]
  [ 50  86 110]
  ...
  [ 69  40  43]
  [ 72  41  40]
  [ 75  42  39]]

 [[ 66  63  88]
  [ 88 114 131]
  [ 63  86 112]
  ...
  [ 69  40  43]
  [ 72  40  41]
  [ 75  41  41]]

 [[ 44  62  79]
  [ 66  67  95]
  [ 91 118 144]
  ...
  [ 69  40  43]
  [ 71  40  41]
  [ 72  41  40]]

 ...

 [[ 63  94 119]
  [ 62  92 117]
  [ 72 107 133]
  ...
  [ 15  37  62]
  [ 24  41  67]
  [ 24  39  65]]

 [[ 65  96 121]
  [ 63  93 118]
  [ 72 107 133]
  ...
  [ 14  36  61]
  [ 23  40  66]
  [ 22  37  63]]

 [[ 67 101 125]
  [ 64  95 120]
  [ 72 107 133]
  ...
  [ 14  36  61]
  [ 22  39  65]
  [ 24  37  63]]]


## How do we save images we edit in OpenCV?

In [11]:
# Simply use 'imwrite' Specifying the file name and the image to be saved
cv2.imwrite('output.jpg', input)
cv2.imwrite('output.png', input)

True

In [12]:
cv2.imshow('Hello World', input)
cv2.waitKey()
cv2.destroyAllWindows()