# Let's Take a Closer Look at Color Spaces 

You may have remembered we talked about images being stored in RGB (Red Green Blue) color Spaces. Let's take a look at that in OpenCV

## First thing to remember about OpenCV's RGB is that it's BGR

 
Lets look at the image shape again. The '3L'

In [2]:
import cv2
import numpy as np

image = cv2.imread('./images/input.jpg')

## Lets look at the individual color levels for the first pixel(0,0)

In [3]:
# BGR Values for the first 0,0 pixel
B, G, R = image[10, 50]
print(B, G, R)
print(image.shape)

70 45 49
(427, 640, 3)


In [7]:
image[0][0]

array([ 81, 115, 139], dtype=uint8)

### 
Let's see what happens when we convert it to grayscale

In [13]:
gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print(gray_img.shape)
print(gray_img[10, 50])

(427, 640)
49


#### 
it's now only two dimensions. Each pixel coordinate has only one value (previously 3) with a range of 0 to 255

In [11]:
gray_img[0, 0]

118

## Another useful color space is HSV
infact HSV is very useful in color filtering

In [14]:
#H: 0-180, S: 0 - 255, V: 0-255
image = cv2.imread('./images/input.jpg')
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

cv2.imshow('HSV image', hsv_image)
cv2.imshow('Hue channel', hsv_image[:, :, 0])
cv2.imshow('Saturation channel', hsv_image[:, :, 1])
cv2.imshow('Value channel', hsv_image[:, :, 2])

cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
print(hsv_image[:, :, 0])

[[ 18  12  18 ... 123 119 117]
 [176  18  14 ... 123 121 120]
 [ 15   1  15 ... 123 121 119]
 ...
 [ 17  16  17 ...  14  12  11]
 [ 17  16  17 ...  14  12  11]
 [ 18  17  17 ...  14  12  10]]


## Let's now explore looking at individual channels in an RGB image 

In [5]:
image = cv2.imread('./images/input.jpg')

# OpenCV's 'split' function splites the image into each color index
B, G, R  = cv2.split(image)

print(B.shape)
cv2.imshow("Red", R)
cv2.imshow("Green", G)
cv2.imshow("Blue", B)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Let's re-make the original image,
merged = cv2.merge([B, G, R])
cv2.imshow("Merged", merged)

# Let's amplify the blue color
merged = cv2.merge([B+100, G, R])
cv2.imshow("Merged with Blue Amplified", merged)

cv2.waitKey()
cv2.destroyAllWindows()

(427, 640)


In [10]:
import cv2
import numpy as np

B, G, R = cv2.split(image)

# Let's create a matrix of zeros
# with dimensions of the image h x w
zeros = np.zeros(image.shape[:2], dtype="uint8")

cv2.imshow("Red", cv2.merge([zeros, zeros, R]))
cv2.imshow("Green", cv2.merge([zeros, G, zeros]))
cv2.imshow("Blue", cv2.merge([B, zeros, zeros]))

cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
print(image.shape[:3])

(427, 640, 3)
